---
driver:
  name: ec2

provisioner:
  name: shell

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-12.10
  - name: ubuntu-13.04
  - name: ubuntu-13.10
  - name: ubuntu-14.04
  # - name: centos-6.4
  # - name: debian-7.1.0

suites:
  - name: default
